stages:
  - stage: BuildAndPush
    jobs:
      - job: DockerBuild
        pool:
          name: 'Default'
        steps:
          - checkout: self

          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              command: login
              containerRegistry: 'online-boutique'

          - ${{ each service in parameters.services }}:
              - script: echo "Service: ${{ service }}"
                displayName: 'Print Service ${{ service }}'

          - ${{ each service in parameters.services }}:
              - task: Docker@2
                displayName: 'Build and Push ${{ service }}'
                inputs:
                  command: buildAndPush
                  repository: '${{ service }}'
                  dockerfile: 'src/${{ service }}/Dockerfile'
                  containerRegistry: 'online-boutique'
                  tags: '$(Build.BuildId)'
