trigger:
  branches:
    include:
      - main

parameters:
  - name: services
    type: object
    default:
      - adservice
      - cartservice
      - checkoutservice
      - currencyservice
      - emailservice
      - frontend
      - paymentservice
      - productcatalogservice
      - recommendationservice
      - shippingservice

variables:
  azureContainerRegistry: 'chiomaacr.azurecr.io'
  imageTag: '$(Build.BuildId)'

stages:
  - stage: BuildAndPush
    displayName: 'Build and Push All Microservices'
    jobs:
      - job: DockerBuild
        displayName: 'Build & Push Docker Images'
        # ✅ Use your self-hosted agent pool name here
        pool:
          name: 'Default'  # 🔥 Replace with your agent pool name if different

        steps:
          - checkout: self

          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              command: login
              containerRegistry: 'online-boutique'  # 🔥 Replace this with your actual service connection name

          # ✅ Loop through services dynamically
          - ${{ each service in parameters.services }}:
              - task: Docker@2
                displayName: 'Build and Push ${{ service }}'
                inputs:
                  command: buildAndPush
                  repository: '${{ service }}'
                  dockerfile: 'microservices/${{ service }}/Dockerfile'
                  containerRegistry: 'online-boutique' # 🔥 Same here
                  tags: '$(imageTag)'
