trigger:
  branches:
    include:
      - main

parameters:
  - name: services
    type: object
    default:
      - adservice
      - cartservice
      - checkoutservice
      - currencyservice
      - emailservice
      - frontend
      - loadgenerator
      - paymentservice
      - productcatalogservice
      - recommendationservice
      - shippingservice
      - shoppingassistantservice

variables:
  azureContainerRegistry: 'chiomaacr.azurecr.io'
  imageTag: '$(Build.BuildId)'

stages:
  - stage: BuildAndPush
    displayName: 'Build and Push All Microservices'
    jobs:
      - job: DockerBuild
        displayName: 'Build & Push Docker Images'
        pool:
          name: 'Default'   # ✅ Your agent pool is named Default
        steps:
          - checkout: self

          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              command: login
              containerRegistry: 'online-boutique'   # ✅ Your service connection name

          # ✅ Loop through microservices dynamically
          - ${{ each service in parameters.services }}:
              - task: Docker@2
                displayName: 'Build and Push ${{ service }}'
                inputs:
                  command: buildAndPush
                  repository: '${{ service }}'
                  dockerfile: 'src/${{ service }}/Dockerfile'
                  containerRegistry: 'online-boutique'
                  tags: '$(imageTag)'
