trigger:
  branches:
    include:
      - main

parameters:
  - name: services
    type: object
    default:
      - adservice
      - cartservice
      - checkoutservice
      - currencyservice
      - emailservice
      - frontend
      - loadgenerator
      - paymentservice
      - productcatalogservice
      - recommendationservice
      - shippingservice
      - shoppingassistantservice

stages:
  - stage: BuildAndPush
    jobs:
      - job: DockerBuild
        pool:
          name: 'Default'  # Your self-hosted agent pool name
        steps:
          - checkout: self

          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              command: login
              containerRegistry: 'online-boutique'  # Your ACR service connection name

          - script: echo "Services = ${{ format('{0}', parameters.services) }}"
            displayName: 'Print Services List'

          - ${{ each service in parameters.services }}:
              - task: Docker@2
                displayName: 'Build and Push ${{ service }}'
                inputs:
                  command: buildAndPush
                  repository: '${{ service }}'
                  dockerfile: 'src/${{ service }}/Dockerfile'
                  containerRegistry: 'online-boutique'
                  tags: '$(Build.BuildId)'
