parameters:
- name: services
  type: object
  displayName: 'List of services and image tags'

trigger: none  # Manual trigger or CI trigger passing params

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'chiomaacr.azurecr.io'

steps:
- checkout: self
  persistCredentials: true
  clean: true
  fetchDepth: 0

# ✅ Optional Debug - Print received services
- script: |
    echo "✅ DEBUG: Services received => ${{ convertToJson(parameters.services) }}"
  displayName: 'DEBUG - Print received services'

# ✅ Fail fast if services is empty
- ${{ if eq(length(parameters.services), 0) }}:
  - script: |
      echo "❌ ERROR: No services provided. Please pass the services parameter."
      exit 1
    displayName: 'FAIL - Missing services input'

# ✅ Update image and force timestamp change to trigger Git commit
- ${{ each service in parameters.services }}:
  - script: |
      file="kubernetes-manifests/${{ service.name }}.yaml"
      if [[ -f "$file" ]]; then
        echo "✅ Updating image for ${{ service.name }} to tag ${{ service.imageTag }}"
        sed -i "s|image: $(acrName)/${{ service.name }}:.*|image: $(acrName)/${{ service.name }}:${{ service.imageTag }}|" "$file"
        
        # ✅ Force a Git change by appending timestamp comment
        echo "✅ Appending timestamp to force Git change"
        echo "# Deployed on $(date -u)" >> "$file"
      else
        echo "⚠️ $file not found. Skipping."
      fi
    displayName: 'Update Image Tag and Force Change for ${{ service.name }}'

# ✅ Commit and push with dynamic branch detection
- script: |
    branch=$(git rev-parse --abbrev-ref HEAD)
    echo "✅ Current branch is: $branch"

    # Handle detached HEAD
    if [[ "$branch" == "HEAD" ]]; then
      echo "⚠️ Detached HEAD. Checking out main branch..."
      git checkout main || git checkout -b main
      branch="main"
    fi

    git config user.name "chiomanwanedo"
    git config user.email "chiomavanessa8@gmail.com"
    git add kubernetes-manifests/*.yaml

    if git diff --cached --quiet; then
      echo "✅ No changes to commit."
    else
      git commit -m '✅ Update image tags and deployment timestamp'
      echo "✅ Committed changes."
    fi

    git push origin $branch || echo "✅ Nothing to push or branch missing."
  displayName: 'Commit and Push Updated Manifests'
