parameters:
- name: services
  type: object
  displayName: 'List of services and image tags'

trigger: none  # Run manually or trigger from CI

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'chiomaacr.azurecr.io'

steps:
- checkout: self

# Loop through each service and update its deployment manifest
- ${{ each service in parameters.services }}:
  - script: |
      echo "Updating image for ${{ service.name }} to tag ${{ service.imageTag }}"
      sed -i "s|image: $(acrName)/${{ service.name }}:.*|image: $(acrName)/${{ service.name }}:${{ service.imageTag }}|" k8s/${{ service.name }}-deployment.yaml
    displayName: 'Update Image Tag for ${{ service.name }}'

# Commit and push the changes back to the GitOps repo
- script: |
    git config user.name "chiomanwanedo"
    git config user.email "chiomavanessa8@gmail.com"
    git add k8s/*-deployment.yaml
    git commit -m "Update image tags for multiple services"
    git push origin main
  displayName: 'Commit and Push Updated Manifests'
