apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: currencyservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chioma-dev/microservices-k8s-manifests.git  # Update with your actual repo
    targetRevision: main
    path: currencyservice  # Folder in your repo where this YAML lives
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true      # ✅ Removes resources deleted from Git
      selfHeal: true   # ✅ Auto-fixes drift to match Git source
# Deployed on Tue Mar 25 22:03:27 UTC 2025
